import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import à partir de @ c'est notre alias pour le dossier src
import Header from "@/components/Header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Meteo Widget",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* children va contenir le JSX de :
				- page.tsx
				- error.tsx si un des composants throw un erreur 
				- loading.tsx si un des composnats est asynchrone et renvoie une promesse non fullfilled  */}
				<div className="p-4 bg-gradient-to-br from-blue-500 to-cyan-500 min-h-dvh">
					<Header />
					{children}
				</div>
			</body>
		</html>
	);
}
